# Generated by Django 3.1.3 on 2020-11-27 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagiapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileguru',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_teacher',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='ProfileGuru',
        ),
    ]
