# Generated by Django 3.1.3 on 2020-11-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagiapi', '0003_auto_20201128_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='reward',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
