# Generated by Django 3.1.3 on 2020-11-28 05:58

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagiapi', '0004_auto_20201128_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='materi',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/static/materi_course'), upload_to=''),
        ),
    ]
