# Generated by Django 3.1.3 on 2020-11-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagiapi', '0005_auto_20201128_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='materi',
            field=models.FileField(upload_to='materi_course/'),
        ),
    ]
