# Generated by Django 3.1.3 on 2020-11-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagiapi', '0006_auto_20201128_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='materi',
            field=models.FileField(upload_to=''),
        ),
    ]
