# Generated by Django 3.1.3 on 2020-12-16 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagiapi', '0011_auto_20201216_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertemuan', models.CharField(blank=True, max_length=50, null=True)),
                ('link', models.URLField(blank=True)),
                ('modul', models.FileField(upload_to='modul_course/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagiapi.course')),
            ],
        ),
    ]
